/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DanhSachRouteImport } from './routes/danh-sach'
import { Route as ExcelRouteImport } from './routes/excel'
import { Route as ThemRouteImport } from './routes/them'
import { Route as EmIdRouteImport } from './routes/em.$id'
import { Route as EmIdSuaRouteImport } from './routes/em.$id.sua'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DanhSachRoute = DanhSachRouteImport.update({
  id: '/danh-sach',
  path: '/danh-sach',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcelRoute = ExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemRoute = ThemRouteImport.update({
  id: '/them',
  path: '/them',
  getParentRoute: () => rootRouteImport,
} as any)
const EmIdRoute = EmIdRouteImport.update({
  id: '/em/$id',
  path: '/em/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmIdSuaRoute = EmIdSuaRouteImport.update({
  id: '/sua',
  path: '/sua',
  getParentRoute: () => EmIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/danh-sach': typeof DanhSachRoute
  '/excel': typeof ExcelRoute
  '/them': typeof ThemRoute
  '/em/$id': typeof EmIdRouteWithChildren
  '/em/$id/sua': typeof EmIdSuaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/danh-sach': typeof DanhSachRoute
  '/excel': typeof ExcelRoute
  '/them': typeof ThemRoute
  '/em/$id': typeof EmIdRouteWithChildren
  '/em/$id/sua': typeof EmIdSuaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/danh-sach': typeof DanhSachRoute
  '/excel': typeof ExcelRoute
  '/them': typeof ThemRoute
  '/em/$id': typeof EmIdRouteWithChildren
  '/em/$id/sua': typeof EmIdSuaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/danh-sach' | '/excel' | '/them' | '/em/$id' | '/em/$id/sua'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/danh-sach' | '/excel' | '/them' | '/em/$id' | '/em/$id/sua'
  id:
    | '__root__'
    | '/'
    | '/danh-sach'
    | '/excel'
    | '/them'
    | '/em/$id'
    | '/em/$id/sua'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DanhSachRoute: typeof DanhSachRoute
  ExcelRoute: typeof ExcelRoute
  ThemRoute: typeof ThemRoute
  EmIdRoute: typeof EmIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/danh-sach': {
      id: '/danh-sach'
      path: '/danh-sach'
      fullPath: '/danh-sach'
      preLoaderRoute: typeof DanhSachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excel': {
      id: '/excel'
      path: '/excel'
      fullPath: '/excel'
      preLoaderRoute: typeof ExcelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/them': {
      id: '/them'
      path: '/them'
      fullPath: '/them'
      preLoaderRoute: typeof ThemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em/$id': {
      id: '/em/$id'
      path: '/em/$id'
      fullPath: '/em/$id'
      preLoaderRoute: typeof EmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em/$id/sua': {
      id: '/em/$id/sua'
      path: '/sua'
      fullPath: '/em/$id/sua'
      preLoaderRoute: typeof EmIdSuaRouteImport
      parentRoute: typeof EmIdRoute
    }
  }
}

interface EmIdRouteChildren {
  EmIdSuaRoute: typeof EmIdSuaRoute
}

const EmIdRouteChildren: EmIdRouteChildren = {
  EmIdSuaRoute: EmIdSuaRoute,
}

const EmIdRouteWithChildren = EmIdRoute._addFileChildren(EmIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DanhSachRoute: DanhSachRoute,
  ExcelRoute: ExcelRoute,
  ThemRoute: ThemRoute,
  EmIdRoute: EmIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
